language: ruby

rvm:
  - 2.1.2

services:
  - mongodb

bundler_args: --without development

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_script:
  - mv config/mongoid_example.yml config/mongoid.yml

branches:
  only:
    - master
    - production
