13:
  capacity: 1300
  birth_rate: 0.15
  death_rate: 0.05
  size: 650
  type: 13
8:
  capacity: 800
  birth_rate: 0.15
  death_rate: 0.05
  size: 400
  type: 8
5:
  capacity: 500
  birth_rate: 0.15
  death_rate: 0.05
  size: 250
  type: 5
3:
  capacity: 300
  birth_rate: 0.15
  death_rate: 0.05
  size: 150
  type: 3
2:
  capacity: 200
  birth_rate: 0.15
  death_rate: 0.05
  size: 100
  type: 2
1:
  capacity: 100
  birth_rate: 0.15
  death_rate: 0.05
  size: 50
  type: 1
0:
  capacity: 20
  birth_rate: 0.15
  death_rate: 0.05
  size: 10
  type: 0
