development:
  root_path: fixme
  log_file: log/level.log
  log_level: DEBUG
  socket_file: tmp/sockets/players.sock
test:
  root_path: fixme
  log_file: log/level_test.log
  log_level: DEBUG
  socket_file: tmp/sockets/players.sock
production:
  root_path: fixme
  log_file: log/level.log
  log_level: INFO
  socket_file: tmp/sockets/players.sock
