development:
  secret_key_base: fixme
  github_client_id: fixme
  github_secret: fixme
  airbrake_api_key: fixme
  newrelic_key: fixme
  codeclimate_repo: fixme
  mail:
    address: fixme
    domain: fixme
    user_name: fixme
    password: fixme
    port: fixme
    authentication: fixme
    enable_starttls_auto: true
test:
  secret_key_base: fixme
  github_client_id: fixme
  github_secret: fixme
  airbrake_api_key: fixme
  newrelic_key: fixme
  codeclimate_repo: fixme
  mail:
    address: fixme
    domain: fixme
    user_name: fixme
    password: fixme
    port: fixme
    authentication: fixme
    enable_starttls_auto: true
production:
  secret_key_base: fixme
  github_client_id: fixme
  github_secret: fixme
  airbrake_api_key: fixme
  newrelic_key: fixme
  codeclimate_repo: fixme
  mail:
    address: fixme
    domain: fixme
    user_name: fixme
    password: fixme
    port: fixme
    authentication: fixme
    enable_starttls_auto: true
