---
chdir: "/path/to/dawning"
environment: developement
timeout: 30
log: "/path/to/dawning/log/thin.log"
pid: tmp/pids/thin.pid
max_conns: 1024
max_persistent_conns: 100
require: []
wait: 30
threadpool_size: 20
servers: 1
daemonize: true
socket: tmp/sockets/thin.sock
