---
pid: tmp/pids/thin.pid
socket: tmp/sockets/thin.sock
timeout: 30
wait: 30
log: log/thin.log
max_conns: 1024
require: []
threadpool_size: 20
environment: production
max_persistent_conns: 100
server: 2
daemonize: true
chdir: /path/to/current
