time_unit: 60
sim_loop:
  duration: 15
world:
  width: 50
  height: 100
  builder:
    vegetation:
      config: vegetation.yml
      grounding: 5
      clusters:
        -
          times: 10
          vegetation: 2
          count: 10
        -
          times: 20
          vegetation: 3
          count: 30
        -
          times: 50
          vegetation: 8
          count: 80
        -
          times: 50
          vegetation: 13
          count: 40
    flora:
      # type_1, type_2, type_3 -> 9, 6, 3 / per 200 fields
      per_fields: 200
      types:
        -
          type: 'banana_1'
          spread:
            -
              vegetation: 13
              amount: 5
            -
              vegetation: 8
              amount: 3
            -
              vegetation: 5
              amount: 1
        -
          type: 'banana_2'
          spread:
            -
              vegetation: 13
              amount: 3
            -
              vegetation: 8
              amount: 3
        -
          type: 'banana_3'
          spread:
            -
              vegetation: 13
              amount: 2
            -
              vegetation: 8
              amount: 1
    fauna:
      # type_1, type_2, type_3 -> 8, 4, 2 / per 200 fields
      per_fields: 200
      types:
        -
          type: 'rabbit'
          spread:
            -
              vegetation: 13
              amount: 4
            -
              vegetation: 8
              amount: 3
            -
              vegetation: 5
              amount: 1
        -
          type: 'gazelle'
          spread:
            -
              vegetation: 13
              amount: 2
            -
              vegetation: 8
              amount: 2
        -
          type: 'mammoth'
          spread:
            -
              vegetation: 13
              amount: 2
        # just guessing
        - type: 'leopard'
          spread:
            -
              vegetation: 13
              amount: 4
            -
              vegetation: 8
              amount: 2
            -
              vegetation: 5
              amount: 1
dropzones:
  bot_1:
    from:  0
    to:   19
  gateway:
    from: 20
    to:   39
  transit:
    from: 50
    to:   49
  players:
    from: 60
    to:   79
  bot_2:
    from: 80
    to:   99
