# type_1, type_2, type_3 -> 8, 4, 2 / per 200 fields
per_fields: 200
types:
  -
    type: Rabbit
    spread:
      -
        vegetation: 13
        amount: 4
      -
        vegetation: 8
        amount: 3
      -
        vegetation: 5
        amount: 1
  -
    type: Gazelle
    spread:
      -
        vegetation: 13
        amount: 2
      -
        vegetation: 8
        amount: 2
  -
    type: Mammoth
    spread:
      -
        vegetation: 13
        amount: 2
  # just guessing
  - type: Leopard
    spread:
      -
        vegetation: 13
        amount: 4
      -
        vegetation: 8
        amount: 2
      -
        vegetation: 5
        amount: 1
