time_unit: 5
world:
  width: 15
  height: 15
  builder:
    vegetation:
      grounding: 5
      clusters:
        -
          times: 1
          vegetation: 8
          count: 10
        -
          times: 2
          vegetation: 13
          count: 4
