time_unit: 5
sim_loop:
  duration: 120
world:
  width: 15
  height: 15
  vegetation:
    classes: vegetation.yml
    builder: test_vegetation_builder.yml
  flora:
    classes: flora.yml
    builder: test_flora_builder.yml
  fauna:
    classes: animal.yml
    builder: test_fauna_builder.yml
dropzones:
  bot_1:
    from:  0
    to:    3
  gateway:
    from:  4
    to:    6
  transit:
    from:  7
    to:    9
  players:
    from: 10
    to:   12
  bot_2:
    from: 13
    to:   15
